### ISSUE TITLE
Duplicated Class and old version one 

### ISSUE THREAD

**Issue by havefun77612** [myinnos/ImageSaveandShare#2]
**I'm facing a problem calling the ImageSaveandShare library**

Now when I call the library it raises a conflict with an existing library which is  grid layout library 
the class name is **coordinator layout** version used please update to coordinatorlayout:28.0.0

**Comment by myinnos** [comment]
Hello @havefun77612 

This lib didn't use coordinator layout.
Please upgrade to latest version i.e, [1.0.4](https://github.com/myinnos/ImageSaveandShare/releases/tag/1.0.4) which upgraded to androidX

Also, read [READ.ME](https://github.com/myinnos/ImageSaveandShare/blob/master/README.md) updated recently
